### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by jabrena** [gitt-3-pat/documentacion#15]
http://kripken.github.io/talks/
https://revealjs.com/pdf-export/
https://github.com/hakimel/reveal.js/blob/master/css/print/pdf.scss
https://github.com/swartzrock/reveal.js-to-pdf
https://www.sassmeister.com/

https://www.wjst.de/blog/sciencesurf/2019/11/print-your-reveal-js-presentation/

https://revealjs.com/demo/?print-pdf

```
brew install node
npm install -g decktape
decktape -s 1280x720 reveal http://myserver/reveal.php reveal.pdf
```

Migrated original issue to the right repository:
https://github.com/gitt-3-pat/gitt-3-pat.github.io/issues/2

**Comment by jabrena** [comment]
```
decktape -s 1280x800 reveal https://gitt-3-pat.github.io/documentacion/tema-0/ tema0.pdf
```

**Comment by jabrena** [comment]
- decktape -s 1280x800 reveal https://gitt-3-pat.github.io/documentacion/tema-0/ tema-0.pdf
- decktape -s 1280x800 reveal https://gitt-3-pat.github.io/documentacion/tema-1/ tema-1.pdf

**Comment by jabrena** [comment]
In M1 computers, the process fails:

```
jabrena@Juans-MacBook-Pro documentacion % decktape -s 1280x800 reveal https://gitt-3-pat.github.io/documentacion/tema-0/ tema0.pdf
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/homebrew/lib/node_modules/decktape/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/decktape/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:185:82)
    at ChildProcess.emit (node:events:378:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Comment by jabrena** [comment]
```
docker run --rm -t -v `pwd`:/slides astefanutti/decktape https://gitt-3-pat.github.io/documentacion/tema-0/ tema0.pdf
```

https://github.com/puppeteer/puppeteer/issues/1947

**Comment by jabrena** [comment]
```
docker run --rm -t -v pwd:/slides astefanutti/decktape https://gitt-3-pat.github.io/documentacion/tema-9/ tema-9.pdf
Loading page https://gitt-3-pat.github.io/documentacion/tema-9/ ...
Loading page finished with status: 200
Reveal JS plugin activated
Printing slide #/11/2   (32/32) ...
Printed 32 slides
```
